version: 2.1

jobs:
  build-push:
    docker:
      - image: circleci/golang:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image.
          command: docker build . -t highsupply/docker-alpine-node:latest
      - run:
          name: Push Docker image.
          command: docker push highsupply/docker-alpine-node:latest

workflows:
  build-push:
    jobs:
      - build-push
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-push
